spring.application.name=SmartLMS

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://dpg-d49c0iqli9vc739p1470-a/smart_lms
spring.datasource.username=smart_lms_user
spring.datasource.password=m0NZIemJffiTrRXj4GsxfpjHEQXaxcp6

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true


# File properties
file.upload-dir=uploads
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Flask RAG server URL
rag.server.url=http://localhost:5000/upload

# Server Port
server.port=8080

