spring.application.name=SmartLMS

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/lms_db
spring.datasource.username=lms_user
spring.datasource.password=lms12345

# Hibernate auto schema creation
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# File properties
file.upload-dir=uploads
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Flask RAG server URL
rag.server.url=http://localhost:5000/upload

# Server Port
server.port=8080

