spring.application.name=SmartLMS


spring.application.name=SmartLMS
server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=pTxzSJwaaQVEDGFbdSlgTwZlGbELsJJX
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


server.port=${PORT:8080}
spring.application.name=SmartLMS



# Optional: connection pool tuning
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5


# File properties
file.upload-dir=uploads
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Flask RAG server URL
rag.server.url=http://localhost:5000/upload

